backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Description, name: description, widget: text}]}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/team/index.md"
        label: "Research Team Page"
        name: "team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team-page"}
          - {label: "Title", name: "title", widget: "string", default: "Research Team"}
          - {label: Members, name: members, widget: list, fields: [{label: Name, name: name, widget: text}, {label: Text, name: text, widget: markdown}, {label: Image, name: image, widget: image}, {label: Url, name: url, widget: text}]}
      - file: "src/pages/activities/index.md"
        label: "Activities Page"
        name: "activities"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "activity-page"}
          - {label: "Title", name: "title", widget: "string", default: "Activites"}
          - {label: Activites, name: activities, widget: list, fields: [{label: Name, name: name, widget: text}, {label: Text, name: text, widget: markdown}, {label: Image, name: image, widget: image}]}
      - file: "src/pages/dates/index.md"
        label: "Important dates"
        name: "dates"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "dates-page"}
          - {label: "Title", name: "title", widget: "string", default: "Important dates"}
          - label: Dates
            name: dates
            widget: list
            fields:
              - {label: Name, name: name, widget: text}
              - label: Date
                name: date
                widget: "datetime"
                dateFormat: "DD.MM.YYYY"
                timeFormat: false

